[package]
name = "example-java"
version = "0.1.0"
authors = ["Chris Ballinger <chrisballinger@gmail.com>"]

[lib]
name = "example_java"
crate-type = ["cdylib", "rlib"]

[dependencies]
jni = "0.10"
libc = "0.2"
example-generic = { path = "../generic" }
